// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rasa.Context.World;

namespace Rasa.Migrations.SqliteWorld
{
    [DbContext(typeof(SqliteWorldContext))]
    [Migration("20260918060000_MissionAreaLinks")]
    partial class MissionAreaLinks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Rasa.Structures.World.CreatureLootEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Chance")
                        .HasColumnType("REAL")
                        .HasColumnName("chance");

                    b.Property<uint>("CreatureId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_id");

                    b.Property<uint>("ItemTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_template_id");

                    b.Property<uint>("StacksizeMax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stacksize_max");

                    b.Property<uint>("StacksizeMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stacksize_min");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(96)")
                        .HasColumnName("comment");

                    b.HasKey("Id");

                    b.ToTable("creature_loot");
                });

            modelBuilder.Entity("Rasa.Structures.World.ArmorClassEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<uint>("MaxDamageAbsorbed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_damage_absorbed");

                    b.Property<uint>("MinDamageAbsorbed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_damage_absorbed");

                    b.Property<int>("RegenRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("regen_rate");

                    b.HasKey("Id");

                    b.ToTable("armorclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.ContentAreaEntry", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<double>("HalfHeight")
                        .HasColumnType("REAL")
                        .HasColumnName("half_height");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL")
                        .HasColumnName("radius");

                    b.Property<byte>("Shape")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shape");

                    b.HasKey("Id");

                    b.ToTable("content_area");
                });

            modelBuilder.Entity("Rasa.Structures.World.ContentConditionEntry", b =>
                {
                    b.Property<uint>("ConditionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_id");

                    b.Property<byte>("OrGroup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("or_group");

                    b.Property<byte>("TermIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("term_index");

                    b.Property<string>("FactKey")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("fact_key");

                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<bool>("Negate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("negate");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<uint>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value");

                    b.HasKey("ConditionId", "OrGroup", "TermIndex");

                    b.ToTable("content_condition");
                });

            modelBuilder.Entity("Rasa.Structures.World.ContentItemSetEntry", b =>
                {
                    b.Property<uint>("ItemSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_set_id");

                    b.Property<uint>("ItemTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_template_id");

                    b.Property<uint>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.HasKey("ItemSetId", "ItemTemplateId");

                    b.ToTable("content_item_set");
                });

            modelBuilder.Entity("Rasa.Structures.World.ContentLocationEntry", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<byte>("Purpose")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purpose");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL")
                        .HasColumnName("rotation");

                    b.HasKey("Id");

                    b.ToTable("content_location");
                });

            modelBuilder.Entity("Rasa.Structures.World.ContentMapSettingEntry", b =>
                {
                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<byte>("Instancing")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instancing");

                    b.HasKey("MapContextId");

                    b.ToTable("content_map_setting");
                });

            modelBuilder.Entity("Rasa.Structures.World.ContentPlacementEntry", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("AlternateState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alternate_state");

                    b.Property<uint>("AlternateStateConditionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alternate_state_condition_id");

                    b.Property<byte>("Behavior")
                        .HasColumnType("INTEGER")
                        .HasColumnName("behavior");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<uint>("CreatureId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_id");

                    b.Property<uint>("EntityClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entity_class_id");

                    b.Property<uint>("EscortMissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("escort_mission_id");

                    b.Property<uint>("FuseMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fuse_ms");

                    b.Property<uint>("HitPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit_points");

                    b.Property<uint>("InitialState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initial_state");

                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<uint>("LootItemSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loot_item_set_id");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<uint>("NameOverrideId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("name_override_id");

                    b.Property<uint>("NpcPackageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("npc_package_id");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<uint>("PresentConditionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("present_condition_id");

                    b.Property<uint>("RespawnMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("respawn_ms");

                    b.Property<uint>("RestoreMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("restore_ms");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL")
                        .HasColumnName("rotation");

                    b.Property<uint>("UsableConditionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usable_condition_id");

                    b.Property<byte>("UsableKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usable_kind");

                    b.Property<uint>("WindupMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("windup_ms");

                    b.HasKey("Id");

                    b.ToTable("content_placement");
                });

            modelBuilder.Entity("Rasa.Structures.World.ContentRuleActionEntry", b =>
                {
                    b.Property<uint>("RuleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rule_id");

                    b.Property<byte>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<byte>("Action")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action");

                    b.Property<uint>("AudioSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("audio_set_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credits");

                    b.Property<uint>("Experience")
                        .HasColumnType("INTEGER")
                        .HasColumnName("experience");

                    b.Property<string>("FactKey")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("fact_key");

                    b.Property<int>("FactValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fact_value");

                    b.Property<bool>("Forced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("forced");

                    b.Property<uint>("GreetingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("greeting_id");

                    b.Property<uint>("ItemSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_set_id");

                    b.Property<uint>("LocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_id");

                    b.Property<uint>("LogosId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("logos_id");

                    b.Property<byte>("LogosProtocol")
                        .HasColumnType("INTEGER")
                        .HasColumnName("logos_protocol");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("NpcNameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("npc_name_id");

                    b.Property<uint>("PlacementId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("placement_id");

                    b.Property<uint>("StateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_id");

                    b.Property<uint>("TutorialId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tutorial_id");

                    b.HasKey("RuleId", "Sequence");

                    b.ToTable("content_rule_action");
                });

            modelBuilder.Entity("Rasa.Structures.World.ContentRuleEntry", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("AreaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("area_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<uint>("ConditionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_id");

                    b.Property<byte>("Event")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<uint>("PlacementId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("placement_id");

                    b.Property<uint>("StateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_id");

                    b.HasKey("Id");

                    b.ToTable("content_rule");
                });

            modelBuilder.Entity("Rasa.Structures.World.CreatureActionEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ActionArgId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action_arg_id");

                    b.Property<uint>("ActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action_id");

                    b.Property<uint>("Cooldown")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cooldown");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<uint>("MaxDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_damage");

                    b.Property<uint>("MinDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_damage");

                    b.Property<double>("RangeMax")
                        .HasColumnType("REAL")
                        .HasColumnName("range_max");

                    b.Property<double>("RangeMin")
                        .HasColumnType("REAL")
                        .HasColumnName("range_min");

                    b.Property<uint>("Windup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("windup");

                    b.HasKey("Id");

                    b.ToTable("creature_action");
                });

            modelBuilder.Entity("Rasa.Structures.World.CreatureAppearanceEntry", b =>
                {
                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Class_id");

                    b.Property<uint>("Color")
                        .HasColumnType("INTEGER")
                        .HasColumnName("color");

                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("SlotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_id");

                    b.ToTable("creature_appearance");
                });

            modelBuilder.Entity("Rasa.Structures.World.CreatureEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("Action1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action1");

                    b.Property<uint>("Action2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action2");

                    b.Property<uint>("Action3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action3");

                    b.Property<uint>("Action4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action4");

                    b.Property<uint>("Action5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action5");

                    b.Property<uint>("Action6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action6");

                    b.Property<uint>("Action7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action7");

                    b.Property<uint>("Action8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action8");

                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<uint>("Faction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("faction");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<uint>("MaxHitPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_hp");

                    b.Property<uint>("NameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("name_id");

                    b.Property<uint>("RunSpeed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_speed");

                    b.Property<uint>("WalkSpeed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("walk_speed");

                    b.HasKey("Id");

                    b.ToTable("creature");
                });

            modelBuilder.Entity("Rasa.Structures.World.CreatureStatEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Armor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("armor");

                    b.Property<int>("Body")
                        .HasColumnType("INTEGER")
                        .HasColumnName("body");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER")
                        .HasColumnName("health");

                    b.Property<int>("Mind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mind");

                    b.Property<int>("Spirit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("spirit");

                    b.HasKey("Id");

                    b.ToTable("creature_stat");
                });

            modelBuilder.Entity("Rasa.Structures.World.EntityClassEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AugList")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("aug_list");

                    b.Property<byte>("ClassCollisionRole")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_collision_role");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("class_name");

                    b.Property<uint>("MeshId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mesh_id");

                    b.Property<byte>("TargetFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_flag");

                    b.HasKey("Id");

                    b.ToTable("entityclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.EquipableClassEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("SlotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_id");

                    b.HasKey("Id");

                    b.ToTable("equipableclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.ExperienceForLevelEntry", b =>
                {
                    b.Property<uint>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("level")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.None);

                    b.Property<long>("Experience")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("experience");

                    b.HasKey("Level");

                    b.ToTable("player_exp_for_level");
                });

            modelBuilder.Entity("Rasa.Structures.World.FootlockerEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("comment");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL")
                        .HasColumnName("rotation");

                    b.HasKey("Id");

                    b.ToTable("footlocker");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemClassEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("DragAudioSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drag_audio_set_id");

                    b.Property<uint>("DropAudioSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drop_audio_set_id");

                    b.Property<byte>("HidenInventoryFlag")
                        .HasColumnType("bit")
                        .HasColumnName("hidden_invenotry_flag");

                    b.Property<uint>("InventoryIconStringId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inventory_icon_string_id");

                    b.Property<byte>("IsConsumableFlag")
                        .HasColumnType("bit")
                        .HasColumnName("is_consumable_flag");

                    b.Property<uint>("LootValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loot_value");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_hp");

                    b.Property<uint>("StackSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_size");

                    b.HasKey("Id");

                    b.ToTable("itemclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateArmorEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArmorValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("armor_value");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate_armor");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("BoundToCharacterFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bound_to_character_flag");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buy_price");

                    b.Property<byte>("HasAccountUniqueFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_account_unique_flag");

                    b.Property<byte>("HasBoEFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_boe_flag");

                    b.Property<byte>("HasCharacterUniqueFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_character_unique_flag");

                    b.Property<byte>("HasSellableFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_sellable_flag");

                    b.Property<byte>("InventoryCategory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inventory_category");

                    b.Property<byte>("NotPlacableInLockboxFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("not_placable_in_lockbox_flag");

                    b.Property<byte>("NotTradableFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("not_tradable_flag");

                    b.Property<byte>("QualityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_id");

                    b.Property<int>("SellPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sell_price");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateItemClassEntry", b =>
                {
                    b.Property<uint>("ItemTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("itemTemplateId")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.None);

                    b.Property<uint>("ItemClass")
                        .HasColumnType("int(11)")
                        .HasColumnName("itemClassId");

                    b.HasKey("ItemTemplateId");

                    b.ToTable("itemtemplate_itemclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateRequirementEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("RequirementType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("req_type");

                    b.Property<byte>("RequirementValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("req_value");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate_requirement");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateRequirementRaceEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("RaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("race_id");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate_requirement_race");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateRequirementSkillEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_id");

                    b.Property<byte>("SkillLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_level");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate_requirement_skill");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateResistanceEntry", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("ResistanceType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resistance_type");

                    b.Property<int>("ResistanceValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resistance_value");

                    b.ToTable("itemtemplate_resistance");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateWeaponEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("AeRadius")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ae_radius");

                    b.Property<uint>("AeType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ae_type");

                    b.Property<double>("AimRate")
                        .HasColumnType("REAL")
                        .HasColumnName("aim_rate");

                    b.Property<uint>("AltActionArgId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_action_arg_id");

                    b.Property<uint>("AltActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_action_id");

                    b.Property<uint>("AltAeRadius")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_ae_radius");

                    b.Property<uint>("AltAeType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_ae_type");

                    b.Property<uint>("AltDamageType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_damage_type");

                    b.Property<uint>("AltMaxDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_max_damage");

                    b.Property<uint>("AltRange")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_range");

                    b.Property<uint>("AmmoPerShot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ammo_per_shot");

                    b.Property<uint>("AttackType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attack_type");

                    b.Property<uint>("CoolRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cool_rate");

                    b.Property<double>("HeatPerShot")
                        .HasColumnType("REAL")
                        .HasColumnName("heat_per_shot");

                    b.Property<uint>("Range")
                        .HasColumnType("INTEGER")
                        .HasColumnName("range");

                    b.Property<uint>("RecoilAmount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recoil_amount");

                    b.Property<uint>("Recovery")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recovery");

                    b.Property<uint>("Refire")
                        .HasColumnType("INTEGER")
                        .HasColumnName("refire");

                    b.Property<uint>("ReloadTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reload_time");

                    b.Property<uint>("ReuseOverride")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reuse_override");

                    b.Property<uint>("ToolType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tool_type");

                    b.Property<uint>("Windup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("windup");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate_weapon");
                });

            modelBuilder.Entity("Rasa.Structures.World.KraftwerksEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("comment");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL")
                        .HasColumnName("rotation");

                    b.HasKey("Id");

                    b.ToTable("kraftwerks");
                });

            modelBuilder.Entity("Rasa.Structures.World.LogosEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.HasKey("Id");

                    b.ToTable("logos");
                });

            modelBuilder.Entity("Rasa.Structures.World.MapInfoEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<uint>("BaseRegion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_region");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("map_name");

                    b.Property<uint>("MapVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_version");

                    b.HasKey("Id");

                    b.ToTable("map_info");
                });

            modelBuilder.Entity("Rasa.Structures.World.MapLinkEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("comment");

                    b.Property<uint>("DestMapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dest_map_context_id");

                    b.Property<double>("DestPosX")
                        .HasColumnType("REAL")
                        .HasColumnName("dest_pos_x");

                    b.Property<double>("DestPosY")
                        .HasColumnType("REAL")
                        .HasColumnName("dest_pos_y");

                    b.Property<double>("DestPosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("dest_pos_z");

                    b.Property<double>("DestRotation")
                        .HasColumnType("REAL")
                        .HasColumnName("dest_rotation");

                    b.Property<byte>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL")
                        .HasColumnName("radius");

                    b.HasKey("Id");

                    b.ToTable("map_link");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<uint>("GiverId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("giver_id");

                    b.Property<byte>("GroupType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_type");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<bool>("RadioCompleteable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("radio_completeable");

                    b.Property<uint>("ReciverId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reciver_id");

                    b.Property<bool>("Shareable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shareable");

                    b.HasKey("Id");

                    b.ToTable("npc_mission");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionObjectiveBindingEntry", b =>
                {
                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<byte>("BindingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("binding_id");

                    b.Property<uint>("ActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action_id");

                    b.Property<uint>("AreaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("area_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<byte>("CounterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("counter_id");

                    b.Property<uint>("CreatureId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_id");

                    b.Property<bool>("DestroyingHitOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnName("destroying_hit_only");

                    b.Property<byte>("EquipMatch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("equip_match");

                    b.Property<uint>("ItemSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_set_id");

                    b.Property<uint>("ItemTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_template_id");

                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<uint>("PlacementId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("placement_id");

                    b.Property<uint>("TargetState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_state");

                    b.HasKey("MissionId", "ObjectiveId", "BindingId");

                    b.ToTable("npc_mission_objective_binding");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionObjectiveConversationEntry", b =>
                {
                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<uint>("NpcPackageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("npc_package_id");

                    b.Property<uint>("PlayerFlagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("player_flag_id");

                    b.Property<uint>("ConvoType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("convo_type");

                    b.HasKey("MissionId", "ObjectiveId", "NpcPackageId", "PlayerFlagId", "ConvoType");

                    b.ToTable("npc_mission_objective_conversation");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionObjectiveCounterEntry", b =>
                {
                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<byte>("CounterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("counter_id");

                    b.Property<int>("InitialValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initial_value");

                    b.Property<int>("TargetValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_value");

                    b.HasKey("MissionId", "ObjectiveId", "CounterId");

                    b.ToTable("npc_mission_objective_counter");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionObjectiveEntry", b =>
                {
                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("comment");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_required");

                    b.Property<uint?>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<bool?>("RevealedOnAccept")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revealed_on_accept");

                    b.HasKey("MissionId", "ObjectiveId");

                    b.ToTable("npc_mission_objective");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionObjectiveIndicatorEntry", b =>
                {
                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<byte>("IndicatorIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("indicator_index");

                    b.Property<uint>("IndicatorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("indicator_id");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL")
                        .HasColumnName("radius");

                    b.Property<bool>("Show3d")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_3d");

                    b.HasKey("MissionId", "ObjectiveId", "IndicatorIndex");

                    b.ToTable("npc_mission_objective_indicator");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionObjectiveTimerEntry", b =>
                {
                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<uint>("LimitSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("limit_seconds");

                    b.Property<byte>("OnExpire")
                        .HasColumnType("INTEGER")
                        .HasColumnName("on_expire");

                    b.HasKey("MissionId", "ObjectiveId");

                    b.ToTable("npc_mission_objective_timer");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionObjectiveTransitionEntry", b =>
                {
                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("CompletedObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_objective_id");

                    b.Property<uint>("RevealedObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revealed_objective_id");

                    b.HasKey("MissionId", "CompletedObjectiveId", "RevealedObjectiveId");

                    b.ToTable("npc_mission_objective_transition");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionPrerequisiteEntry", b =>
                {
                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<byte>("OrGroup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("or_group");

                    b.Property<uint>("RequiredMissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("required_mission_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<byte>("RequiredState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("required_state");

                    b.HasKey("MissionId", "OrGroup", "RequiredMissionId");

                    b.ToTable("npc_mission_prerequisite");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionRewardEntry", b =>
                {
                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credits");

                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ItemTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_template_id");

                    b.Property<uint>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.ToTable("npc_mission_reward");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcPackageEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<uint>("PackageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("package_id");

                    b.HasKey("Id");

                    b.ToTable("npc_package");
                });

            modelBuilder.Entity("Rasa.Structures.World.RandomNameEntry", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint(3)")
                        .HasColumnName("type");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint(3)")
                        .HasColumnName("gender");

                    b.HasKey("Name", "Type", "Gender");

                    b.ToTable("player_random_name");
                });

            modelBuilder.Entity("Rasa.Structures.World.SpawnPoolEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("AnimType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anim_type");

                    b.Property<uint>("Creature1Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_1_Id");

                    b.Property<byte>("Creature1MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_1_max_count");

                    b.Property<byte>("Creature1MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_1_min_count");

                    b.Property<uint>("Creature2Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_2_Id");

                    b.Property<byte>("Creature2MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_2_max_count");

                    b.Property<byte>("Creature2MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_2_min_count");

                    b.Property<uint>("Creature3Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_3_Id");

                    b.Property<byte>("Creature3MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_3_max_count");

                    b.Property<byte>("Creature3MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_3_min_count");

                    b.Property<uint>("Creature4Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_4_Id");

                    b.Property<byte>("Creature4MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_4_max_count");

                    b.Property<byte>("Creature4MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_4_min_count");

                    b.Property<uint>("Creature5Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_5_Id");

                    b.Property<byte>("Creature5MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_5_max_count");

                    b.Property<byte>("Creature5MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_5_min_count");

                    b.Property<uint>("Creature6Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_6_Id");

                    b.Property<byte>("Creature6MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_6_max_count");

                    b.Property<byte>("Creature6MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_6_min_count");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<byte>("Mode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mode");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<uint>("RespawnTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("respown_time");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL")
                        .HasColumnName("rotation");

                    b.HasKey("Id");

                    b.ToTable("spawnpool");
                });

            modelBuilder.Entity("Rasa.Structures.World.TeleporterEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("description");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL")
                        .HasColumnName("rotation");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("teleporter");
                });

            modelBuilder.Entity("Rasa.Structures.World.VendorEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("PackageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("package_id");

                    b.HasKey("Id");

                    b.ToTable("vendor");
                });

            modelBuilder.Entity("Rasa.Structures.World.VendorItemEntry", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ItemTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_template_id");

                    b.ToTable("vendor_item");
                });

            modelBuilder.Entity("Rasa.Structures.World.WeaponClassEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("AmmoClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ammo_class_id");

                    b.Property<uint>("AttackActionArgId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attack_action_arg_id");

                    b.Property<uint>("AttackActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attack_action_id");

                    b.Property<uint>("ClipSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("clip_size");

                    b.Property<byte>("DamageType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("damage_type");

                    b.Property<byte>("DrawActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("draw_action_id");

                    b.Property<int>("MaxDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_damage");

                    b.Property<int>("MinDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_damage");

                    b.Property<bool>("RangeType")
                        .HasColumnType("bit")
                        .HasColumnName("range_type");

                    b.Property<bool>("RecoveryOverride")
                        .HasColumnType("bit")
                        .HasColumnName("recovery_override");

                    b.Property<byte>("ReloadActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reload_action_id");

                    b.Property<bool>("ReloadOverride")
                        .HasColumnType("bit")
                        .HasColumnName("reload_override");

                    b.Property<bool>("ReuseOverride")
                        .HasColumnType("bit")
                        .HasColumnName("reuse_override");

                    b.Property<byte>("StowActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stow_action_id");

                    b.Property<bool>("UnknownArg1")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg1");

                    b.Property<bool>("UnknownArg2")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg2");

                    b.Property<bool>("UnknownArg3")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg3");

                    b.Property<bool>("UnknownArg4")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg4");

                    b.Property<bool>("UnknownArg5")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg5");

                    b.Property<uint>("UnknownArg6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unk_arg6");

                    b.Property<bool>("UnknownArg7")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg7");

                    b.Property<uint>("UnknownArg8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unk_arg8");

                    b.Property<int>("Velocity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("velocity");

                    b.Property<uint>("WeaponAnimConditionCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weapon_anim_condition_code");

                    b.Property<uint>("WeaponTemplatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weapon_template_id");

                    b.Property<bool>("WindupOverride")
                        .HasColumnType("bit")
                        .HasColumnName("windup_override");

                    b.HasKey("Id");

                    b.ToTable("weaponclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.MapRegionEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(96)")
                        .HasColumnName("comment");

                    b.Property<byte>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<double>("HalfX")
                        .HasColumnType("REAL")
                        .HasColumnName("half_x");

                    b.Property<double>("HalfZ")
                        .HasColumnType("REAL")
                        .HasColumnName("half_z");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<double>("MaxY")
                        .HasColumnType("REAL")
                        .HasColumnName("max_y");

                    b.Property<double>("MinY")
                        .HasColumnType("REAL")
                        .HasColumnName("min_y");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL")
                        .HasColumnName("radius");

                    b.Property<uint>("RegionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("region_id");

                    b.Property<byte>("Shape")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shape");

                    b.Property<byte>("Underground")
                        .HasColumnType("INTEGER")
                        .HasColumnName("underground");

                    b.HasKey("Id");

                    b.ToTable("map_region");
                });
#pragma warning restore 612, 618
        }
    }
}
